# Generated by Django 5.2.11 on 2026-03-12 07:22

import blog.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=blog.storage_backends.SupabaseStorage(), upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=blog.storage_backends.SupabaseStorage(), upload_to='avatars/'),
        ),
    ]
